deployments:
  k8s:
    kubernetes_manifest: ./kube-deployment.yml
    deployment_type: kubernetes
    kubernetes_default_pod: web
    pipelines:
      - k8s:
          scripts:
           - echo true
           - ls -la
