deployments:
  k8s:
    kubernetes_manifest: ./kube-deployment.yml
    deployment_type: kubernetes
    kubernetes_default_pod: web
    pipelines:
      - k8s:
          scripts:
            web:
              - echo "true"
              - ls -la
      - all:
          scripts:
            - ls -la
