deployments:
  k8s:
    deployment_type: kubernetes
    kubernetes_port_mapping: svc/web:8081
    install:
      - kubectl set env pods --all -e TEST=$SQUASH_BRANCH
      - kubectl apply -f ./kube-deployment.yml
      - squash--k8s-route
