deployments:
  App:
    kubernetes_build_image: 
      - nginx:$TAG
      - guestbook:$TAG
    use_kubernetes_registry: true
    deployment_type: kubernetes
    kubernetes_default_pod: nginx
    kubernetes_port_mapping:
      - pod/guestbook:8888
    subdomain_port_mapping:
      - sub:8888
